name: csn_tv_display
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1


environment:
  sdk: ^3.5.3



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.6.1
  socket_io_client: ^3.0.2
  intl: ^0.20.1
  marquee: ^2.3.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  widget_marquee: ^0.0.8
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3




flutter:
  uses-material-design: true

  assets:
    - assets/svgs/

